"""Initial schema

Revision ID: f85d3a20e3ac
Revises: None
Create Date: 2026-05-29 19:32:30.089710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85d3a20e3ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_actions',
    sa.Column('action_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('confidence_composite', sa.Float(), nullable=True),
    sa.Column('confidence_signals', sa.Text(), nullable=True),
    sa.Column('human_decision', sa.String(length=20), nullable=True),
    sa.Column('human_id', sa.String(length=50), nullable=True),
    sa.Column('decision_ts', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('endpoint_id_proposed', sa.String(length=50), nullable=True),
    sa.Column('endpoint_id_approved', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('biomedical_concepts',
    sa.Column('bc_id', sa.String(length=50), nullable=False),
    sa.Column('bc_name', sa.String(length=100), nullable=False),
    sa.Column('bc_category', sa.String(length=50), nullable=True),
    sa.Column('cosmos_bc_id', sa.String(length=100), nullable=True),
    sa.Column('sdtmig_class', sa.String(length=50), nullable=True),
    sa.Column('coding_system', sa.String(length=100), nullable=True),
    sa.Column('bc_definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('bc_id')
    )
    op.create_table('estimands',
    sa.Column('estimand_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ice_strategy', sa.Text(), nullable=True),
    sa.Column('target_population', sa.Text(), nullable=True),
    sa.Column('variable_of_interest', sa.Text(), nullable=True),
    sa.Column('summary_measure', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('estimand_id')
    )
    op.create_table('execution_snapshots',
    sa.Column('snapshot_id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.Column('sdtmig_version', sa.String(length=20), nullable=True),
    sa.Column('adamig_version', sa.String(length=20), nullable=True),
    sa.Column('python_version', sa.String(length=20), nullable=True),
    sa.Column('sas_version', sa.String(length=20), nullable=True),
    sa.Column('rule_hash_manifest', sa.Text(), nullable=True),
    sa.Column('metadata_db_hash', sa.String(length=64), nullable=True),
    sa.Column('environment_hash', sa.String(length=64), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('pending_queue',
    sa.Column('queue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_table('programs',
    sa.Column('program_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('generated_path', sa.Text(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('compiled_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('where_clauses',
    sa.Column('where_clause_id', sa.String(length=50), nullable=False),
    sa.Column('dataset', sa.String(length=50), nullable=True),
    sa.Column('variable', sa.String(length=50), nullable=True),
    sa.Column('filter_operator', sa.String(length=10), nullable=True),
    sa.Column('filter_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('where_clause_id')
    )
    op.create_table('endpoint_definitions',
    sa.Column('endpoint_id', sa.String(length=50), nullable=False),
    sa.Column('bc_id', sa.String(length=50), nullable=True),
    sa.Column('estimand_id', sa.String(length=50), nullable=True),
    sa.Column('endpoint_type', sa.String(length=20), nullable=True),
    sa.Column('analysis_concept', sa.String(length=50), nullable=True),
    sa.Column('sap_reference', sa.String(length=100), nullable=True),
    sa.Column('criteria_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bc_id'], ['biomedical_concepts.bc_id'], ),
    sa.ForeignKeyConstraint(['estimand_id'], ['estimands.estimand_id'], ),
    sa.PrimaryKeyConstraint('endpoint_id')
    )
    op.create_table('variables',
    sa.Column('variable', sa.String(length=50), nullable=False),
    sa.Column('dataset', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('datatype', sa.String(length=20), nullable=True),
    sa.Column('bc_id', sa.String(length=50), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('controlled_terminology', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bc_id'], ['biomedical_concepts.bc_id'], ),
    sa.PrimaryKeyConstraint('variable', 'dataset')
    )
    op.create_table('analysis_results',
    sa.Column('analysis_id', sa.String(length=50), nullable=False),
    sa.Column('endpoint_id', sa.String(length=50), nullable=True),
    sa.Column('dataset', sa.String(length=50), nullable=True),
    sa.Column('paramcd', sa.String(length=8), nullable=True),
    sa.Column('where_clause_id', sa.String(length=50), nullable=True),
    sa.Column('stat_method', sa.String(length=100), nullable=True),
    sa.Column('stat_test', sa.String(length=100), nullable=True),
    sa.Column('tfl_reference', sa.String(length=50), nullable=True),
    sa.Column('estimand_id', sa.String(length=50), nullable=True),
    sa.Column('arm_display_label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint_definitions.endpoint_id'], ),
    sa.ForeignKeyConstraint(['estimand_id'], ['estimands.estimand_id'], ),
    sa.ForeignKeyConstraint(['where_clause_id'], ['where_clauses.where_clause_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('derivation_rules',
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('endpoint_id', sa.String(length=50), nullable=True),
    sa.Column('target_variable', sa.String(length=50), nullable=False),
    sa.Column('logic_type', sa.String(length=50), nullable=False),
    sa.Column('assessor', sa.String(length=20), nullable=True),
    sa.Column('criteria_type', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('logic_definition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint_definitions.endpoint_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('protocol_objectives',
    sa.Column('obj_id', sa.String(length=50), nullable=False),
    sa.Column('obj_type', sa.String(length=20), nullable=True),
    sa.Column('obj_text', sa.Text(), nullable=False),
    sa.Column('m11_section', sa.String(length=50), nullable=True),
    sa.Column('endpoint_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint_definitions.endpoint_id'], ),
    sa.PrimaryKeyConstraint('obj_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol_objectives')
    op.drop_table('derivation_rules')
    op.drop_table('analysis_results')
    op.drop_table('variables')
    op.drop_table('endpoint_definitions')
    op.drop_table('where_clauses')
    op.drop_table('programs')
    op.drop_table('pending_queue')
    op.drop_table('execution_snapshots')
    op.drop_table('estimands')
    op.drop_table('biomedical_concepts')
    op.drop_table('ai_actions')
    # ### end Alembic commands ###
