%macro derive_iupd_flag(outds=, inds=, targetvar=, iupd_dt=, confirmation_dt=, confirmation_window=);
data &outds;
    set &inds;
    if not missing(&iupd_dt) and not missing(&confirmation_dt) then do;
        if &confirmation_dt - &iupd_dt >= &confirmation_window then do;
            &targetvar = "CONFIRMED";
        end;
        else do;
            &targetvar = "UNCONFIRMED";
        end;
    end;
    else if not missing(&iupd_dt) then do;
        &targetvar = "UNCONFIRMED";
    end;
    else do;
        &targetvar = "NONE";
    end;
run;
%mend derive_iupd_flag;
